name: Build Staging

on:
  push:
    branches:
      - main
  
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build
        run: docker-compose -f docker-compose-staging.yml build --parallel
      - name: Push
        run: docker-compose -f docker-compose-staging.yml push
