name: Build Staging

on:
  push:
    branches:
      - main
  
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build
        run: docker-compose -f docker-compose-staging.yml build --parallel
      - name: Push
        run: docker-compose -f docker-compose-staging.yml push
